-- MySQL Script generated by MySQL Workbench
-- Wed Jul  1 13:38:27 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema spring_security_custom_user_demo
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema gestione_candidature
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `gestione_candidature` ;

-- -----------------------------------------------------
-- Schema gestione_candidature
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gestione_candidature` DEFAULT CHARACTER SET latin1 ;
USE `gestione_candidature` ;

-- -----------------------------------------------------
-- Table `gestione_candidature`.`sede`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestione_candidature`.`sede` (
  `id_città` INT NOT NULL AUTO_INCREMENT,
  `nomeCittà` VARCHAR(45) NOT NULL,
  `via` VARCHAR(55) NOT NULL,
  `cap` INT NOT NULL,
  `numeroCivico` INT NOT NULL,
  PRIMARY KEY (`id_città`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `gestione_candidature`.`utente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestione_candidature`.`utente` (
  `id_user` INT UNSIGNED NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `cognome` VARCHAR(45) NOT NULL,
  `numeroTel` CHAR(12) NOT NULL,
  `mail` VARCHAR(55) NOT NULL,
  `ruolo` ENUM('hr', 'manager', 'admin', 'not_set') NOT NULL DEFAULT 'not_set',
  `sedeAssegnamento` INT NOT NULL,
  PRIMARY KEY (`id_user`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  UNIQUE INDEX `NumeroTel_UNIQUE` (`numeroTel` ASC) VISIBLE,
  INDEX `fk_sedeAssegnamento_idx` (`sedeAssegnamento` ASC) VISIBLE,
  CONSTRAINT `fk_sedeAssegnamento`
    FOREIGN KEY (`sedeAssegnamento`)
    REFERENCES `gestione_candidature`.`sede` (`id_città`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `gestione_candidature`.`candidato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestione_candidature`.`candidato` (
  `codiceFiscale` VARCHAR(16) NOT NULL,
  `sato_candidatura` ENUM('new', 'assegnato_hr', 'assegnato_manager', 'in_valutazione', 'assunto', 'rigettato') NOT NULL DEFAULT 'new',
  `nome` VARCHAR(45) NOT NULL,
  `cognome` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(12) NOT NULL,
  `email` VARCHAR(55) NOT NULL,
  `dataNascita` DATE NOT NULL,
  `tipoContratto` ENUM('tempo_indeterminato', 'tempo_determinato', 'somministrazione', 'a_chiamata', 'a_progetto', 'accessorio', 'apprendistato', 'tirocinio_formativo_e_orientamento', 'part-time', 'not_set') NOT NULL DEFAULT 'not_set',
  `ral` FLOAT NOT NULL DEFAULT '0',
  `tempo_preavviso_giorni` INT NOT NULL DEFAULT '10' COMMENT 'Numero di giorni preavviso',
  `tipoOfferta` ENUM('lavoro', 'stage', 'candidatura_spontanea') NOT NULL,
  `canale_provenienza` VARCHAR(150) NOT NULL,
  `aspettative` VARCHAR(100) NULL DEFAULT NULL,
  `note` MEDIUMTEXT NULL DEFAULT NULL,
  `curriculum` BLOB NOT NULL COMMENT 'curriculum o caricato direttamente o si potrebbe salvare il percorso del file',
  `supervisore` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codiceFiscale`),
  INDEX `fk_Candidato_utente1_idx` (`supervisore` ASC) VISIBLE,
  CONSTRAINT `fk_Candidato_utente1`
    FOREIGN KEY (`supervisore`)
    REFERENCES `gestione_candidature`.`utente` (`username`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `gestione_candidature`.`ruoli`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestione_candidature`.`ruoli` (
  `id_ruoli` INT UNSIGNED NOT NULL,
  `nome_ruolo` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_ruoli`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `gestione_candidature`.`schedavalutazione`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestione_candidature`.`schedavalutazione` (
  `dataColloquio` DATE NULL DEFAULT NULL,
  `CVAllegato` ENUM('si', 'no') NULL DEFAULT 'no',
  `periodoPreavviso` INT NULL DEFAULT '10',
  `inquadramentoRichiesto` VARCHAR(75) NULL DEFAULT NULL,
  `inquadramentoAttuale` VARCHAR(75) NULL DEFAULT NULL,
  `retribuzioneRichiesta` FLOAT NULL DEFAULT NULL,
  `retribuzioneAttuale` FLOAT NULL DEFAULT '0',
  `note` MEDIUMTEXT NULL DEFAULT NULL,
  `competenza` VARCHAR(75) NULL DEFAULT NULL,
  `lingue` VARCHAR(200) NULL DEFAULT NULL,
  `noteSpostamenti` VARCHAR(145) NULL DEFAULT NULL,
  `motivazioneProfessionale` VARCHAR(145) NULL DEFAULT NULL,
  `motivazioneCambiamento` VARCHAR(145) NULL DEFAULT NULL,
  `esperienzeGenerali` VARCHAR(245) NULL DEFAULT NULL,
  `esperienzePosizione` VARCHAR(245) NULL DEFAULT NULL,
  `presenza` ENUM('insuff', 'suff', 'discreto', 'buono', 'ottimo') NULL DEFAULT NULL,
  `comunicatività` ENUM('insuff', 'suff', 'discreto', 'buono', 'ottimo') NULL DEFAULT NULL,
  `dinamicità` ENUM('insuff', 'suff', 'discreto', 'buono', 'ottimo') NULL DEFAULT NULL,
  `disponibilitàSpostamentiTrasferimenti` ENUM('si', 'no') NULL DEFAULT NULL,
  `sede_preferita` INT NULL DEFAULT NULL,
  `utente_relatore` VARCHAR(45) NOT NULL,
  `candidato_relativo` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`utente_relatore`, `candidato_relativo`),
  INDEX `fk_candidato_idx` (`candidato_relativo` ASC) VISIBLE,
  CONSTRAINT `fk_candidato`
    FOREIGN KEY (`candidato_relativo`)
    REFERENCES `gestione_candidature`.`candidato` (`codiceFiscale`)
    ON UPDATE CASCADE,
  CONSTRAINT `fk_utente_relatore`
    FOREIGN KEY (`utente_relatore`)
    REFERENCES `gestione_candidature`.`utente` (`username`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `gestione_candidature`.`utenti_ruoli`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestione_candidature`.`utenti_ruoli` (
  `id_utenti` INT UNSIGNED NOT NULL,
  `id_ruoli` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_utenti`, `id_ruoli`),
  INDEX `FK_id_ruolo_idx` (`id_ruoli` ASC) VISIBLE,
  CONSTRAINT `FK_id_ruolo`
    FOREIGN KEY (`id_ruoli`)
    REFERENCES `gestione_candidature`.`ruoli` (`id_ruoli`),
  CONSTRAINT `FK_id_utente`
    FOREIGN KEY (`id_utenti`)
    REFERENCES `gestione_candidature`.`utente` (`id_user`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
